--------------------------------------------------------------------------------
-- Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.4
--  \   \         Application : xaw2vhdl
--  /   /         Filename : dcm_40mhz.vhd
-- /___/   /\     Timestamp : 04/07/2013 16:27:16
-- \   \  /  \ 
--  \___\/\___\ 
--
-- Design Name: dcm_40mhz
-- Device: xc3s100e-5cp132
--
-- Module dcm_40mhz
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity dcm_40mhz is
    port ( 
        CLKIN_IN        : in    std_logic; 
        CLKDV_OUT       : out   std_logic; 
--        CLKIN_IBUFG_OUT : out   std_logic; 
        CLK0_OUT        : out   std_logic
    );
end dcm_40mhz;

architecture behavioral of dcm_40mhz is
     signal CLKDV_BUF    : std_logic;
     signal CLKFB_IN     : std_logic;
     signal CLKIN_IBUFG  : std_logic;
     signal CLK0_BUF     : std_logic;
     signal GND_BIT      : std_logic;
begin
     GND_BIT <= '0';
--     CLKIN_IBUFG_OUT <= CLKIN_IBUFG;
     CLK0_OUT <= CLKFB_IN;
     CLKDV_BUFG_INST : BUFG
        port map (
            I=>CLKDV_BUF,
            O=>CLKDV_OUT
        );
     
    CLKIN_IBUFG_INST : IBUFG
        port map (
            I=>CLKIN_IN,
            O=>CLKIN_IBUFG
        );
     
    CLK0_BUFG_INST : BUFG
        port map (
            I=>CLK0_BUF,
            O=>CLKFB_IN
        );
     
    DCM_SP_INST : DCM_SP
        generic map ( 
            CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.5,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 10.000,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"C080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE
        )
        port map (
            CLKFB=>CLKFB_IN,
            CLKIN=>CLKIN_IBUFG,
            DSSEN=>GND_BIT,
            PSCLK=>GND_BIT,
            PSEN=>GND_BIT,
            PSINCDEC=>GND_BIT,
            RST=>GND_BIT,
            CLKDV=>CLKDV_BUF,
            CLKFX=>open,
            CLKFX180=>open,
            CLK0=>CLK0_BUF,
            CLK2X=>open,
            CLK2X180=>open,
            CLK90=>open,
            CLK180=>open,
            CLK270=>open,
            LOCKED=>open,
            PSDONE=>open,
            STATUS=>open
        );

end behavioral;
